name: publish
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@main
        with:
          version: 625d41eb8dbe7d83eabc6ba406dffa84f69e730f
          graph-directory: logseq
          theme-mode: dark
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
